[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "koilang"
description = "Python binding for Koilang"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typing-extensions>=4.5.0",
]
dynamic = ["version"]
authors = [
    { name = "visecy", email = "visecy@visecy.org" },
]
maintainers = [
    { name = "ovizro", email = "ovizro@visecy.org" },
]
license = { text = "Apache-2.0" }
keywords = ["koilang", "binding", "native"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Rust",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Markup"
]

[project.urls]
Homepage = "https://github.com/yourusername/koilang-py"
Repository = "https://github.com/yourusername/koilang-py.git"
Issues = "https://github.com/yourusername/koilang-py/issues"
Documentation = "https://github.com/yourusername/koilang-py#readme"

[project.optional-dependencies]
interactive = [
    "prompt_toolkit>=3.0.0",
]

[project.scripts]
koilang = "koilang.__main__:main"

[tool.uv]
package = true

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "koilang.core"
python-source = "src"
python-packages = ["koilang", "kola"]

[dependency-groups]
dev = [
    "coverage>=7.13.0",
    "maturin>=1.11.5",
    "pytest>=9.0.2",
    "koilang[interactive]",
]

[tool.ruff]
line-length = 127

# Assume Python 3.8
target-version = "py38"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E", "W", "F", "B", "N", "C4", "ASYNC", "ANN0", "ANN2"]
ignore = ["E402"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F4"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",

    # Don't complain aboud typing hint
    "class (\\w+)\\(Protocol\\):",
    "if TYPE_CHECKING:",
    "@(typing\\.)?overload",
]

ignore_errors = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:kola.*",
    "ignore::DeprecationWarning:tests.test_kola",
]
